### ISSUE TITLE
update the readme file

### ISSUE THREAD

**Issue by SoyebSarkar** [BrownGrey/DiscordBot#17]
<img width="699" alt="image" src="https://user-images.githubusercontent.com/96381266/193393476-fdbc5d96-0318-43d7-ad46-45c6fc733e48.png">
The reademe.md file is too sort

**Comment by SoyebSarkar** [comment]
@BrownGrey I want to give it a try, can you please assign me for this? if it is eligible for hacktoberfest-2022

**Comment by BrownGrey** [comment]
Yes But Its Too Small Commit
If you make a proper readme, It can be accepted

**Comment by BrownGrey** [comment]
Its eligible for hacktoberfest

**Comment by SoyebSarkar** [comment]
> Yes But Its Too Small Commit If you make a proper readme, It can be accepted

ok then assign me ... I will try my best

**Comment by BrownGrey** [comment]
> > Yes But Its Too Small Commit If you make a proper readme, It can be accepted
> 
> ok then assign me ... I will try my best

do your best
